### ISSUE TITLE
Create 'initial' and 'completed-workshop' branches

### ISSUE THREAD

**Issue by marisid** [bradreeder/Node-Intro-Workshop#1]
Hey @bradreeder I've worked a bit on your repo. Some suggestions to improve it even further :wink: : 

* I think we should have at least two branches to match different stages of the workshop. In the initial state, there should be no package.json or any server source files, so that these can be created in the code along. So, ideally the initial branch should be merged into master so that it's the default branch once they clone the repo. 

* The 'completed-workshop' branch can stay as a separate branch for anyone to look at after the workshop. I made some changes compared to your completed version - please check my commits for more info. 

* I'm planning to create another intermediate stage where the server files are not modularised, just for reference. 

Let me know what do you think - I'll create the PR now for the initial branch and I've also pushed the completed-workshop branch, so you can have a look :smile:

**Comment by bradreeder** [comment]
Closed by #2 (I believe -- re-open otherwise).
