### ISSUE TITLE
ES6 syntax

### ISSUE THREAD

**Issue by Jbarget** [bradreeder/Node-Intro-Workshop#4]
Heya @bradreeder 

We just started this in Nazareth and quickly got asked about the arrow function.
I feel it would be a good move to remove es6 in the browser as thats what we've been telling them

**Comment by bradreeder** [comment]
Good point. @marisid I forgot that the js file is client-side. We should probably avoid using ES6 on the client-side code to help distinguish to the students the difference between front-end and back-end javascript.

**Comment by marisid** [comment]
@Jbarget thanks for pointing that out!

@bradreeder I've just created a PR for this issue :smile: - please merge when you get the chance.
